"""Regenerate src/data/rooms.ts from the desktop app's theme definitions.

Run from apps/website:  python scripts/sync-rooms.py
The website's room preview is lit with the same values the app uses, so
run this again whenever apps/desktop/.../settings/themes.ts changes.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES = ROOT.parent / 'desktop' / 'src' / 'renderer' / 'src' / 'features' / 'settings' / 'themes.ts'
OUT = ROOT / 'src' / 'data' / 'rooms.ts'

# Short mood line shown beside each room on the site (not in the app's data).
MOODS = {
    'quiet-room': 'Amber & deep walnut',
    'dusty-record': 'Sepia & faded gold',
    'jazz-bar': 'Violet & midnight haze',
    'midnight-apartment': 'Insomnia blue & graphite',
    'rainy-window': 'Slate sky & raindrops',
    'hifi-library': 'Hunter green & brass',
    'concrete-vinyl': 'Raw concrete & terracotta',
    'sunday-morning': 'Warm honey & cream',
}

source = THEMES.read_text(encoding='utf-8')
blocks = re.split(r"\n  \{\n(?=    id: ')", source)[1:9]

rooms = []
for block in blocks:
    def get(key):
        return re.search(key + r":\s*'([^']*)'", block).group(1)

    gradients = re.findall(r"^\s+'((?:radial|linear)-gradient\([^\n]*?)',?$", block, re.M)
    description = get('description')
    rooms.append({
        'id': get('id'),
        'number': get('number'),
        'name': get('name'),
        'description': description[0].upper() + description[1:] + '.',
        'lightingMood': MOODS[get('id')],
        'image': f"media/rooms/room-{get('number')}",
        'accentColor': get('accentColor'),
        'inkColor': get('onSurfaceColor'),
        'mutedColor': get('mutedColor'),
        'plinthColor': get('deckBg'),
        'plinthBorder': get('deckBorder'),
        'isLight': get('vinylMood') == 'light',
        'wallColor': get('bgColor'),
        'light': ', '.join(gradients),
    })

body = json.dumps(rooms, indent=2, ensure_ascii=False)
body = re.sub(r'"(\w+)":', r'\1:', body).replace('"', "'")

OUT.write_text(
    """// GENERATED by scripts/sync-rooms.py from the desktop app's themes.ts - do not edit by hand.

export interface Room {
  id: string
  number: string
  name: string
  description: string
  /** Short mood line shown beside the room name. */
  lightingMood: string
  /** Screenshot of the app in this room, relative to the site base; append `.webp` or `-800.webp`. */
  image: string
  accentColor: string
  /** Text colour on the room's surfaces. */
  inkColor: string
  mutedColor: string
  /** Deck faceplate colour and border. */
  plinthColor: string
  plinthBorder: string
  /** Daylight rooms use a light faceplate and dark text. */
  isLight: boolean
  /** Base wall colour and the layered light that falls across it. */
  wallColor: string
  light: string
}

export const LISTENING_ROOMS: Room[] = """ + body + "\n",
    encoding='utf-8',
)
print(f'wrote {len(rooms)} rooms to {OUT.relative_to(ROOT)}')
