// GENERATED by scripts/sync-rooms.py from the desktop app's themes.ts — do not edit by hand.

export interface Room {
  id: string
  number: string
  name: string
  description: string
  /** Short mood line shown beside the room name. */
  lightingMood: string
  /** Photograph of the room, relative to the site base; append `.webp` or `-480.webp`. */
  image: string
  accentColor: string
  /** Text colour on the room's surfaces. */
  inkColor: string
  mutedColor: string
  /** Deck faceplate colour and border. */
  plinthColor: string
  plinthBorder: string
  /** Daylight rooms use a light faceplate and dark text. */
  isLight: boolean
  /** Base wall colour and the layered light that falls across it. */
  wallColor: string
  light: string
}

export const LISTENING_ROOMS: Room[] = [
  {
    id: 'quiet-room',
    number: '01',
    name: 'Warm Walnut Studio',
    description: 'Amber lamplight, walnut grain, late-night warmth.',
    lightingMood: 'Amber & deep walnut',
    image: 'media/rooms/01_quiet_room',
    accentColor: '#e08e45',
    inkColor: '#faf3ea',
    mutedColor: '#a6866b',
    plinthColor: 'rgba(24, 17, 13, 0.96)',
    plinthBorder: 'rgba(224, 142, 69, 0.18)',
    isLight: false,
    wallColor: '#0f0b07',
    light: 'radial-gradient(ellipse 75% 60% at 85% 15%, rgba(225, 145, 60, 0.22) 0%, rgba(200, 110, 40, 0.08) 45%, transparent 70%), radial-gradient(circle 550px at 60% 50%, rgba(240, 160, 75, 0.09) 0%, transparent 65%), radial-gradient(ellipse 60% 50% at 15% 90%, rgba(140, 75, 25, 0.14) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 10% 10%, rgba(180, 100, 40, 0.06) 0%, transparent 55%), linear-gradient(155deg, #1f140c 0%, #130d08 45%, #0b0704 100%)'
  },
  {
    id: 'dusty-record',
    number: '02',
    name: 'Vintage Amber',
    description: 'Sepia photographs, aged cardboard, faded gold sleeves.',
    lightingMood: 'Sepia & faded gold',
    image: 'media/rooms/02_dusty_record',
    accentColor: '#e5a93c',
    inkColor: '#fbf5e6',
    mutedColor: '#9e8862',
    plinthColor: 'rgba(26, 21, 13, 0.96)',
    plinthBorder: 'rgba(229, 169, 60, 0.2)',
    isLight: false,
    wallColor: '#121008',
    light: 'radial-gradient(ellipse 70% 50% at 50% 10%, rgba(235, 175, 60, 0.20) 0%, rgba(180, 120, 35, 0.07) 50%, transparent 72%), radial-gradient(circle 500px at 65% 52%, rgba(240, 190, 80, 0.10) 0%, transparent 65%), radial-gradient(ellipse 45% 70% at 5% 55%, rgba(160, 110, 35, 0.12) 0%, transparent 60%), radial-gradient(ellipse 45% 70% at 95% 65%, rgba(140, 95, 28, 0.10) 0%, transparent 60%), linear-gradient(175deg, #20190e 0%, #141009 50%, #0c0905 100%)'
  },
  {
    id: 'jazz-bar',
    number: '03',
    name: 'Indigo Jazz Club',
    description: 'Neon signs, velvet booths, smoky violet haze.',
    lightingMood: 'Violet & midnight haze',
    image: 'media/rooms/03_jazz_bar',
    accentColor: '#c084fc',
    inkColor: '#f3efff',
    mutedColor: '#8b7eb8',
    plinthColor: 'rgba(16, 13, 30, 0.96)',
    plinthBorder: 'rgba(192, 132, 252, 0.25)',
    isLight: false,
    wallColor: '#07060e',
    light: 'radial-gradient(ellipse 65% 55% at 75% 12%, rgba(168, 85, 247, 0.28) 0%, rgba(217, 70, 239, 0.12) 38%, transparent 68%), radial-gradient(ellipse 45% 45% at 10% 88%, rgba(234, 115, 30, 0.14) 0%, transparent 58%), radial-gradient(ellipse 55% 45% at 30% 20%, rgba(99, 102, 241, 0.18) 0%, transparent 62%), radial-gradient(circle 480px at 62% 52%, rgba(192, 132, 252, 0.12) 0%, transparent 65%), linear-gradient(155deg, #15112a 0%, #0c0919 50%, #05040a 100%)'
  },
  {
    id: 'midnight-apartment',
    number: '04',
    name: 'Cold Midnight',
    description: 'Insomnia blue, graphite walls, city glow from a window.',
    lightingMood: 'Insomnia blue & graphite',
    image: 'media/rooms/04_midnight_apartment',
    accentColor: '#38bdf8',
    inkColor: '#e6f0fa',
    mutedColor: '#5b7294',
    plinthColor: 'rgba(12, 17, 28, 0.96)',
    plinthBorder: 'rgba(56, 189, 248, 0.2)',
    isLight: false,
    wallColor: '#060810',
    light: 'radial-gradient(ellipse 70% 55% at 90% 8%, rgba(56, 189, 248, 0.22) 0%, rgba(37, 99, 235, 0.12) 40%, transparent 68%), radial-gradient(ellipse 85% 40% at 50% 100%, rgba(30, 58, 138, 0.45) 0%, rgba(14, 165, 233, 0.10) 45%, transparent 75%), radial-gradient(ellipse 40% 65% at 0% 45%, rgba(59, 130, 246, 0.14) 0%, transparent 60%), radial-gradient(circle 520px at 62% 48%, rgba(56, 189, 248, 0.09) 0%, transparent 65%), linear-gradient(165deg, #0e1524 0%, #080c15 50%, #030509 100%)'
  },
  {
    id: 'rainy-window',
    number: '05',
    name: 'Petrichor',
    description: 'Rain on glass, slate sky, warm indoor refuge.',
    lightingMood: 'Slate sky & raindrops',
    image: 'media/rooms/05_rainy_window',
    accentColor: '#7dd3fc',
    inkColor: '#eaf0f8',
    mutedColor: '#64748b',
    plinthColor: 'rgba(18, 23, 34, 0.96)',
    plinthBorder: 'rgba(125, 211, 252, 0.18)',
    isLight: false,
    wallColor: '#0c0f14',
    light: 'radial-gradient(ellipse 90% 55% at 50% 0%, rgba(96, 165, 250, 0.18) 0%, rgba(56, 189, 248, 0.08) 45%, transparent 70%), radial-gradient(ellipse 50% 45% at 88% 85%, rgba(245, 158, 11, 0.15) 0%, transparent 60%), radial-gradient(ellipse 45% 65% at 5% 40%, rgba(14, 165, 233, 0.12) 0%, transparent 58%), radial-gradient(circle 500px at 60% 50%, rgba(125, 211, 252, 0.08) 0%, transparent 62%), linear-gradient(175deg, #161c2b 0%, #0e131d 50%, #07090f 100%)'
  },
  {
    id: 'hifi-library',
    number: '06',
    name: 'Hi-Fi Library',
    description: 'Hunter green walls, mahogany shelves, polished brass.',
    lightingMood: 'Hunter green & brass',
    image: 'media/rooms/06_hifi_library',
    accentColor: '#34d399',
    inkColor: '#e8f8f0',
    mutedColor: '#4d7c62',
    plinthColor: 'rgba(11, 24, 15, 0.96)',
    plinthBorder: 'rgba(52, 211, 153, 0.22)',
    isLight: false,
    wallColor: '#060d06',
    light: 'radial-gradient(ellipse 70% 60% at 25% 15%, rgba(16, 185, 129, 0.25) 0%, rgba(5, 150, 105, 0.09) 45%, transparent 68%), radial-gradient(ellipse 50% 55% at 88% 70%, rgba(217, 140, 35, 0.16) 0%, transparent 58%), radial-gradient(ellipse 80% 40% at 50% 100%, rgba(15, 45, 25, 0.5) 0%, transparent 70%), radial-gradient(circle 500px at 62% 50%, rgba(52, 211, 153, 0.10) 0%, transparent 65%), linear-gradient(160deg, #0e2214 0%, #08150d 50%, #030805 100%)'
  },
  {
    id: 'concrete-vinyl',
    number: '07',
    name: 'Concrete Loft',
    description: 'Raw concrete, warm terracotta, sunlit industrial windows.',
    lightingMood: 'Raw concrete & terracotta',
    image: 'media/rooms/07_concrete_vinyl',
    accentColor: '#c87056',
    inkColor: '#2b2e33',
    mutedColor: '#7a818c',
    plinthColor: 'rgba(235, 237, 240, 0.97)',
    plinthBorder: 'rgba(0, 0, 0, 0.12)',
    isLight: true,
    wallColor: '#d4d6db',
    light: 'radial-gradient(ellipse 75% 65% at 20% 15%, rgba(255,250,240,0.85) 0%, transparent 70%), radial-gradient(ellipse 55% 45% at 90% 90%, rgba(200,112,86,0.18) 0%, transparent 60%), linear-gradient(155deg, #ebedef 0%, #d8dadf 50%, #c4c7cc 100%)'
  },
  {
    id: 'sunday-morning',
    number: '08',
    name: 'Sunday Morning',
    description: 'Linen sheets, warm cream light, slow coffee mornings.',
    lightingMood: 'Warm honey & cream',
    image: 'media/rooms/08_sunday_morning',
    accentColor: '#b45309',
    inkColor: '#3d2a14',
    mutedColor: '#8a6840',
    plinthColor: 'rgba(244, 238, 226, 0.97)',
    plinthBorder: 'rgba(180, 83, 9, 0.14)',
    isLight: true,
    wallColor: '#eee5d5',
    light: 'radial-gradient(ellipse 80% 60% at 18% 0%, rgba(255,248,228,0.92) 0%, transparent 70%), radial-gradient(ellipse 60% 48% at 88% 100%, rgba(182,198,168,0.35) 0%, transparent 65%), linear-gradient(168deg, #f2e8d2 0%, #e9dfc9 50%, #e1d5ba 100%)'
  }
]
